#!/bin/sh

# Clavier fr
setxkbmap fr &
tilda &
nm-applet &
nextcloud &
compton -S --config $HOME/.config/i3/compton.conf &

feh --bg-scale $HOME/.config/i3/classic.png &

#xautolock -detectsleep -time 30 -locker "~/.local/bin/lockscreen off" -locker "sudo pm-hibernate" -nowlocker "~/.local/bin/lockscreen" &

### Touchpad
#synclient TapButton1=1 
# clic droit
#synclient ClickFinger2=3 
synclient TapButton2=3
# Clic milieu
#synclient ClickFinger3=2 
synclient TapButton3=2

synclient VertTwoFingerScroll=1
synclient PalmDetect=1

# Touchpad off
xinput disable 16
xinput disable 17
# Power button off
xinput disable 6

xbacklight -set 70

